testing deploy script #2

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -32,11 +32,19 @@ jobs:
 
           echo "Command ID: $COMMAND_ID"
 
+          # Wait until finished (success OR failure)
           aws ssm wait command-executed \
             --command-id "$COMMAND_ID" \
-            --instance-id "${{ secrets.EC2_INSTANCE_ID }}"
+            --instance-id "${{ secrets.EC2_INSTANCE_ID }}" || true
 
-          echo "---- DEPLOY OUTPUT ----"
+          STATUS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
+            --query "Status" \
+            --output text)
+
+          echo "SSM Status: $STATUS"
+          echo "----- STDOUT -----"
 
           aws ssm get-command-invocation \
             --command-id "$COMMAND_ID" \
@@ -44,10 +52,15 @@ jobs:
             --query "StandardOutputContent" \
             --output text
 
-          echo "---- DEPLOY ERRORS ----"
+          echo "----- STDERR -----"
 
           aws ssm get-command-invocation \
             --command-id "$COMMAND_ID" \
             --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
             --query "StandardErrorContent" \
             --output text
+
+          if [ "$STATUS" != "Success" ]; then
+            echo "Deployment failed"
+            exit 1
+          fi
